# Generated by Django 4.1.5 on 2023-06-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PACK', 'Packing'), ('ARRIVED', 'Arrived At'), ('DISPATCHED', 'Dispatched From'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipmentapp.shipmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipmentapp.shipmentmodel')),
            ],
        ),
    ]
